services:
  mysql:
    image: mysql:latest
    container_name: money-wise-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: 'Asia/Seoul'
    ports:
      - "3305:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  redis:
    image: redis:latest
    container_name: money-wise-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

volumes:
  mysql:
    driver: local