services:
  mysql:
    image: mysql:latest
    container_name: money-wise-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: 'Asia/Seoul'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - money-wise-net
  redis:
    image: redis:latest
    container_name: money-wise-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - money-wise-net
  app:
    container_name: money-wise-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://money-wise-mysql:3306/${MYSQL_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - money-wise-net

volumes:
  mysql:
    driver: local
networks:
  money-wise-net:
    driver: bridge